import { z } from 'zod';
import {
  BotInputSchema,
  BotSessionInputResponseSchema,
  CreateBotSessionRequestSchema,
  CreateBotSessionResponseSchema,
} from '../bot/schemas.js';
import {
  CameraSnapshotPageSchema,
  HealthLiveResponseSchema,
  HealthReadyResponseSchema,
  IntegrationsResponseSchema,
  IsochroneResponseSchema,
  MunicipalitySummarySchema,
  ObjectContractPageSchema,
  PosAppealRefSchema,
  PosExportRequestSchema,
  PosWebhookPayloadSchema,
  ResidentConfirmationRequestSchema,
  RetryNotificationResponseSchema,
  SurveyPageSchema,
} from '../extras/schemas.js';
import { OkSchema } from '../extras/schemas.js';
import {
  AppealIdParamsSchema,
  CsrfHeadersSchema,
  IdParamsSchema,
  MunicipalityIdParamsSchema,
  NotificationIdParamsSchema,
  SessionIdParamsSchema,
} from './auth.js';
import type { CatalogEndpoint } from './types.js';

const csrf = CsrfHeadersSchema;

export const MaxWebhookPayloadSchema = z.object({
  secret: z.string().optional(),
  payload: z.unknown(),
});

export const extrasBotOpsEndpoints: CatalogEndpoint[] = [
  {
    operationId: 'maxWebhook',
    method: 'POST',
    path: '/api/v1/integrations/max/webhook',
    summary: 'Входящее событие MAX',
    tags: ['Bot'],
    auth: 'max-secret',
    permission: null,
    availability: 'not-implemented',
    feature: 'F12',
    body: MaxWebhookPayloadSchema,
    response: OkSchema,
    errorCodes: ['UNAUTHORIZED', 'SCHEMA_ERROR', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'createDevBotSession',
    method: 'POST',
    path: '/api/v1/dev/bot/sessions',
    summary: 'Создать сессию симулятора MAX',
    tags: ['Bot'],
    auth: 'public',
    permission: null,
    availability: 'dev-only',
    feature: 'F11',
    body: CreateBotSessionRequestSchema,
    response: CreateBotSessionResponseSchema,
    errorCodes: ['SCHEMA_ERROR', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'postDevBotInput',
    method: 'POST',
    path: '/api/v1/dev/bot/sessions/{id}/inputs',
    summary: 'Подать ввод в симулятор MAX',
    tags: ['Bot'],
    auth: 'public',
    permission: null,
    availability: 'dev-only',
    feature: 'F11',
    params: SessionIdParamsSchema,
    body: BotInputSchema,
    response: BotSessionInputResponseSchema,
    errorCodes: ['SCHEMA_ERROR', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listPublicSurveys',
    method: 'GET',
    path: '/api/v1/public/surveys',
    summary: 'Опросы жителей',
    tags: ['Extras'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F16',
    response: SurveyPageSchema,
    errorCodes: ['FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getMunicipalitySummary',
    method: 'GET',
    path: '/api/v1/public/municipalities/{id}/summary',
    summary: 'Итоги муниципалитета',
    tags: ['Extras'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F20',
    params: MunicipalityIdParamsSchema,
    response: MunicipalitySummarySchema,
    errorCodes: ['NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getObjectIsochrones',
    method: 'GET',
    path: '/api/v1/public/objects/{id}/isochrones',
    summary: 'Пешеходные изохроны',
    tags: ['Extras'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F21',
    params: IdParamsSchema,
    response: IsochroneResponseSchema,
    errorCodes: ['NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getObjectContracts',
    method: 'GET',
    path: '/api/v1/public/objects/{id}/contracts',
    summary: 'Ссылки на строительные контракты',
    tags: ['Extras'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F22',
    params: IdParamsSchema,
    response: ObjectContractPageSchema,
    errorCodes: ['NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getObjectCameras',
    method: 'GET',
    path: '/api/v1/public/objects/{id}/cameras',
    summary: 'Камеры и датированные снимки',
    tags: ['Extras'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F23',
    params: IdParamsSchema,
    response: CameraSnapshotPageSchema,
    errorCodes: ['NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getAppealPos',
    method: 'GET',
    path: '/api/v1/admin/appeals/{id}/pos',
    summary: 'Связь обращения с ПОС',
    tags: ['POS'],
    auth: 'cookie',
    permission: 'appeals.read',
    availability: 'not-implemented',
    feature: 'F24',
    params: AppealIdParamsSchema,
    response: PosAppealRefSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'exportAppealPos',
    method: 'POST',
    path: '/api/v1/admin/appeals/{id}/pos/export',
    summary: 'Выгрузить обращение во внешнюю систему',
    tags: ['POS'],
    auth: 'cookie',
    permission: 'appeals.reply',
    availability: 'not-implemented',
    feature: 'F24',
    params: AppealIdParamsSchema,
    headers: csrf,
    body: PosExportRequestSchema,
    response: PosAppealRefSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'posWebhook',
    method: 'POST',
    path: '/api/v1/integrations/pos/webhook',
    summary: 'Входящее событие ПОС',
    tags: ['POS'],
    auth: 'internal',
    permission: null,
    availability: 'not-implemented',
    feature: 'F24',
    body: PosWebhookPayloadSchema,
    response: OkSchema,
    errorCodes: ['UNAUTHORIZED', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'createResidentConfirmation',
    method: 'POST',
    path: '/api/v1/internal/resident-confirmations',
    summary: 'Подтверждение устранения от доверенного bot-модуля',
    tags: ['Confirmation'],
    auth: 'internal',
    permission: null,
    availability: 'not-implemented',
    feature: 'F25',
    body: ResidentConfirmationRequestSchema,
    response: OkSchema,
    errorCodes: ['UNAUTHORIZED', 'SCHEMA_ERROR', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'healthLive',
    method: 'GET',
    path: '/health/live',
    summary: 'Процесс жив',
    tags: ['Operations'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F00',
    response: HealthLiveResponseSchema,
    errorCodes: [],
  },
  {
    operationId: 'healthReady',
    method: 'GET',
    path: '/health/ready',
    summary: 'Готовность обязательных хранилищ',
    tags: ['Operations'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F00',
    response: HealthReadyResponseSchema,
    errorCodes: ['INTEGRATION_FAILURE'],
  },
  {
    operationId: 'listAdminIntegrations',
    method: 'GET',
    path: '/api/v1/admin/integrations',
    summary: 'Состояние внешних интеграций',
    tags: ['Operations'],
    auth: 'cookie',
    permission: 'integrations.read',
    availability: 'not-implemented',
    feature: 'F12',
    response: IntegrationsResponseSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'retryNotification',
    method: 'POST',
    path: '/api/v1/admin/notifications/{id}/retry',
    summary: 'Повторить исходящее уведомление',
    tags: ['Operations'],
    auth: 'cookie',
    permission: 'integrations.retry',
    availability: 'not-implemented',
    feature: 'F12',
    params: NotificationIdParamsSchema,
    headers: csrf,
    response: RetryNotificationResponseSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
];
