import {
  AssetAccessResponseSchema,
  CompleteAssetRequestSchema,
  CreateAssetRequestSchema,
  CreateAssetResponseSchema,
  MediaRefSchema,
} from '../media/schemas.js';
import {
  CommitImportRequestSchema,
  CreateImportRequestSchema,
  ImportRecordSchema,
} from '../extras/schemas.js';
import {
  CreateObjectEventRequestSchema,
  ObjectEventPageSchema,
  ObjectEventSchema,
  PatchObjectEventRequestSchema,
  TimelineQuerySchema,
} from '../timeline/schemas.js';
import {
  CreateMetricRequestSchema,
  ObjectMetricPageSchema,
  ObjectMetricSchema,
  PatchMetricRequestSchema,
  PublicMetricsQuerySchema,
} from '../metrics/schemas.js';
import {
  CsrfHeadersSchema,
  IdParamsSchema,
  IfMatchHeadersSchema,
  ObjectEventParamsSchema,
  ObjectMetricParamsSchema,
} from './auth.js';
import type { CatalogEndpoint } from './types.js';

const csrf = CsrfHeadersSchema;
const versioned = CsrfHeadersSchema.and(IfMatchHeadersSchema);

export const importMediaTimelineMetricEndpoints: CatalogEndpoint[] = [
  {
    operationId: 'createImport',
    method: 'POST',
    path: '/api/v1/admin/imports',
    summary: 'Загрузить файл импорта',
    tags: ['Imports'],
    auth: 'cookie',
    permission: 'imports.write',
    availability: 'not-implemented',
    feature: 'F04',
    headers: csrf,
    body: CreateImportRequestSchema,
    response: ImportRecordSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getImport',
    method: 'GET',
    path: '/api/v1/admin/imports/{id}',
    summary: 'Статус импорта',
    tags: ['Imports'],
    auth: 'cookie',
    permission: 'imports.write',
    availability: 'not-implemented',
    feature: 'F04',
    params: IdParamsSchema,
    response: ImportRecordSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'commitImport',
    method: 'POST',
    path: '/api/v1/admin/imports/{id}/commit',
    summary: 'Зафиксировать импорт',
    tags: ['Imports'],
    auth: 'cookie',
    permission: 'imports.write',
    availability: 'not-implemented',
    feature: 'F04',
    params: IdParamsSchema,
    headers: csrf,
    body: CommitImportRequestSchema,
    response: ImportRecordSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'createAsset',
    method: 'POST',
    path: '/api/v1/admin/assets',
    summary: 'Создать запись файла и получить URL загрузки',
    tags: ['Media'],
    auth: 'cookie',
    permission: 'assets.write',
    availability: 'not-implemented',
    feature: 'F02',
    headers: csrf,
    body: CreateAssetRequestSchema,
    response: CreateAssetResponseSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'PAYLOAD_TOO_LARGE', 'UNSUPPORTED_MEDIA', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'completeAsset',
    method: 'POST',
    path: '/api/v1/admin/assets/{id}/complete',
    summary: 'Завершить загрузку и проверить файл',
    tags: ['Media'],
    auth: 'cookie',
    permission: 'assets.write',
    availability: 'not-implemented',
    feature: 'F02',
    params: IdParamsSchema,
    headers: csrf,
    body: CompleteAssetRequestSchema,
    response: MediaRefSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getAssetAccess',
    method: 'GET',
    path: '/api/v1/admin/assets/{id}/access',
    summary: 'Выдать короткоживущий URL после проверки прав',
    tags: ['Media'],
    auth: 'cookie',
    permission: 'assets.read',
    availability: 'not-implemented',
    feature: 'F02',
    params: IdParamsSchema,
    response: AssetAccessResponseSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listPublicObjectEvents',
    method: 'GET',
    path: '/api/v1/public/objects/{id}/events',
    summary: 'Опубликованные события объекта',
    tags: ['Timeline'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F08',
    params: IdParamsSchema,
    query: TimelineQuerySchema.omit({ objectId: true }),
    response: ObjectEventPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listPublicTimeline',
    method: 'GET',
    path: '/api/v1/public/timeline',
    summary: 'Лента опубликованных событий',
    tags: ['Timeline'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F08',
    query: TimelineQuerySchema,
    response: ObjectEventPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'createAdminObjectEvent',
    method: 'POST',
    path: '/api/v1/admin/objects/{id}/events',
    summary: 'Добавить событие в черновик',
    tags: ['Timeline'],
    auth: 'cookie',
    permission: 'objects.write',
    availability: 'not-implemented',
    feature: 'F08',
    params: IdParamsSchema,
    headers: csrf,
    body: CreateObjectEventRequestSchema,
    response: ObjectEventSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'patchAdminObjectEvent',
    method: 'PATCH',
    path: '/api/v1/admin/objects/{id}/events/{eventId}',
    summary: 'Исправить событие черновика',
    tags: ['Timeline'],
    auth: 'cookie',
    permission: 'objects.write',
    availability: 'not-implemented',
    feature: 'F08',
    params: ObjectEventParamsSchema,
    headers: versioned,
    body: PatchObjectEventRequestSchema,
    response: ObjectEventSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listPublicMetrics',
    method: 'GET',
    path: '/api/v1/public/metrics',
    summary: 'Публичные показатели территорий',
    tags: ['Metrics'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F09',
    query: PublicMetricsQuerySchema,
    response: ObjectMetricPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listPublicObjectBenefits',
    method: 'GET',
    path: '/api/v1/public/objects/{id}/benefits',
    summary: 'Польза объекта для территории',
    tags: ['Metrics'],
    auth: 'public',
    permission: null,
    availability: 'not-implemented',
    feature: 'F09',
    params: IdParamsSchema,
    query: PublicMetricsQuerySchema.pick({ dataOrigin: true }),
    response: ObjectMetricPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'createAdminObjectMetric',
    method: 'POST',
    path: '/api/v1/admin/objects/{id}/metrics',
    summary: 'Добавить показатель в черновик',
    tags: ['Metrics'],
    auth: 'cookie',
    permission: 'objects.write',
    availability: 'not-implemented',
    feature: 'F09',
    params: IdParamsSchema,
    headers: csrf,
    body: CreateMetricRequestSchema,
    response: ObjectMetricSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'patchAdminObjectMetric',
    method: 'PATCH',
    path: '/api/v1/admin/objects/{id}/metrics/{metricId}',
    summary: 'Исправить показатель черновика',
    tags: ['Metrics'],
    auth: 'cookie',
    permission: 'objects.write',
    availability: 'not-implemented',
    feature: 'F09',
    params: ObjectMetricParamsSchema,
    headers: versioned,
    body: PatchMetricRequestSchema,
    response: ObjectMetricSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
];
