import {
  ArchiveObjectRequestSchema,
  CreateObjectRequestSchema,
  ObjectDraftPageSchema,
  ObjectDraftSchema,
  ObjectQuerySchema,
  ObjectSummaryPageSchema,
  PatchObjectRequestSchema,
  PublishObjectRequestSchema,
} from '../objects/schemas.js';
import { MapFeatureCollectionSchema } from '../common/geojson.js';
import { ObjectDetailSchema } from '../objects/schemas.js';
import {
  CsrfHeadersSchema,
  IdParamsSchema,
  IfMatchHeadersSchema,
  OptionalIfMatchHeadersSchema,
} from './auth.js';
import type { CatalogEndpoint as Endpoint } from './types.js';

const mutatingHeaders = CsrfHeadersSchema.and(OptionalIfMatchHeadersSchema);
const versionedHeaders = CsrfHeadersSchema.and(IfMatchHeadersSchema);

export const objectEndpoints: Endpoint[] = [
  {
    operationId: 'listPublicObjects',
    method: 'GET',
    path: '/api/v1/public/objects',
    summary: 'Публичный список объектов',
    tags: ['Objects'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F03',
    query: ObjectQuerySchema,
    response: ObjectSummaryPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getPublicMap',
    method: 'GET',
    path: '/api/v1/public/map',
    summary: 'GeoJSON точек опубликованных объектов',
    tags: ['Objects'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F03',
    query: ObjectQuerySchema,
    response: MapFeatureCollectionSchema,
    errorCodes: ['SCHEMA_ERROR', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getPublicObject',
    method: 'GET',
    path: '/api/v1/public/objects/{id}',
    summary: 'Публичная карточка объекта',
    tags: ['Objects'],
    auth: 'public',
    permission: null,
    availability: 'foundation-mock',
    feature: 'F03',
    params: IdParamsSchema,
    query: ObjectQuerySchema.pick({ at: true, dataOrigin: true }),
    response: ObjectDetailSchema,
    errorCodes: ['SCHEMA_ERROR', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listAdminObjects',
    method: 'GET',
    path: '/api/v1/admin/objects',
    summary: 'Список черновиков и объектов для редактора',
    tags: ['Objects'],
    auth: 'cookie',
    permission: 'objects.read',
    availability: 'foundation-mock',
    feature: 'F03',
    query: ObjectQuerySchema,
    response: ObjectDraftPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN'],
  },
  {
    operationId: 'getAdminObject',
    method: 'GET',
    path: '/api/v1/admin/objects/{id}',
    summary: 'Черновик объекта',
    tags: ['Objects'],
    auth: 'cookie',
    permission: 'objects.read',
    availability: 'foundation-mock',
    feature: 'F03',
    params: IdParamsSchema,
    response: ObjectDraftSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND'],
  },
  {
    operationId: 'createAdminObject',
    method: 'POST',
    path: '/api/v1/admin/objects',
    summary: 'Создать черновик объекта',
    tags: ['Objects'],
    auth: 'cookie',
    permission: 'objects.write',
    availability: 'not-implemented',
    feature: 'F03',
    headers: mutatingHeaders,
    body: CreateObjectRequestSchema,
    response: ObjectDraftSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'IDEMPOTENCY_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'patchAdminObject',
    method: 'PATCH',
    path: '/api/v1/admin/objects/{id}',
    summary: 'Обновить черновик объекта',
    tags: ['Objects'],
    auth: 'cookie',
    permission: 'objects.write',
    availability: 'not-implemented',
    feature: 'F03',
    params: IdParamsSchema,
    headers: versionedHeaders,
    body: PatchObjectRequestSchema,
    response: ObjectDraftSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'publishAdminObject',
    method: 'POST',
    path: '/api/v1/admin/objects/{id}/publish',
    summary: 'Опубликовать редакцию объекта',
    tags: ['Objects'],
    auth: 'cookie',
    permission: 'objects.publish',
    availability: 'not-implemented',
    feature: 'F03',
    params: IdParamsSchema,
    headers: versionedHeaders,
    body: PublishObjectRequestSchema,
    response: ObjectDraftSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'archiveAdminObject',
    method: 'POST',
    path: '/api/v1/admin/objects/{id}/archive',
    summary: 'Снять объект с публикации',
    tags: ['Objects'],
    auth: 'cookie',
    permission: 'objects.archive',
    availability: 'not-implemented',
    feature: 'F03',
    params: IdParamsSchema,
    headers: versionedHeaders,
    body: ArchiveObjectRequestSchema,
    response: ObjectDraftSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
];
