import {
  AnalysisRecordSchema,
  RequestAnalysisRequestSchema,
  ReviewAnalysisRequestSchema,
} from '../analysis/schemas.js';
import {
  AppealPageSchema,
  AppealQuerySchema,
  AppealReplyRequestSchema,
  AppealSchema,
  CreateTaskRequestSchema,
  GroupingCandidatesResponseSchema,
  LinkAppealsRequestSchema,
  MergeTasksRequestSchema,
  PatchTaskRequestSchema,
  PriorityFactorsSchema,
  SetPriorityRequestSchema,
  TaskCommentRequestSchema,
  TaskPageSchema,
  TaskQuerySchema,
  TaskSchema,
  TaskTransitionRequestSchema,
} from '../workflow/schemas.js';
import { OkSchema } from '../extras/schemas.js';
import {
  AppealIdParamsSchema,
  CsrfHeadersSchema,
  IdempotencyHeadersSchema,
  IfMatchHeadersSchema,
  TaskIdParamsSchema,
} from './auth.js';
import type { CatalogEndpoint } from './types.js';

const csrf = CsrfHeadersSchema;
const versioned = CsrfHeadersSchema.and(IfMatchHeadersSchema);
const replyHeaders = CsrfHeadersSchema.and(IdempotencyHeadersSchema);

export const workflowEndpoints: CatalogEndpoint[] = [
  {
    operationId: 'listAdminAppeals',
    method: 'GET',
    path: '/api/v1/admin/appeals',
    summary: 'Список обращений',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'appeals.read',
    availability: 'foundation-mock',
    feature: 'F10',
    query: AppealQuerySchema,
    response: AppealPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN'],
  },
  {
    operationId: 'getAdminAppeal',
    method: 'GET',
    path: '/api/v1/admin/appeals/{id}',
    summary: 'Карточка обращения',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'appeals.read',
    availability: 'foundation-mock',
    feature: 'F10',
    params: AppealIdParamsSchema,
    response: AppealSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND'],
  },
  {
    operationId: 'replyAdminAppeal',
    method: 'POST',
    path: '/api/v1/admin/appeals/{id}/replies',
    summary: 'Ответ или уточнение заявителю',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'appeals.reply',
    availability: 'not-implemented',
    feature: 'F10',
    params: AppealIdParamsSchema,
    headers: replyHeaders,
    body: AppealReplyRequestSchema,
    response: AppealSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'IDEMPOTENCY_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listAdminTasks',
    method: 'GET',
    path: '/api/v1/admin/tasks',
    summary: 'Список задач',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'tasks.read',
    availability: 'foundation-mock',
    feature: 'F10',
    query: TaskQuerySchema,
    response: TaskPageSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN'],
  },
  {
    operationId: 'getAdminTask',
    method: 'GET',
    path: '/api/v1/admin/tasks/{id}',
    summary: 'Карточка задачи',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'tasks.read',
    availability: 'foundation-mock',
    feature: 'F10',
    params: TaskIdParamsSchema,
    response: TaskSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND'],
  },
  {
    operationId: 'createAdminTask',
    method: 'POST',
    path: '/api/v1/admin/tasks',
    summary: 'Создать задачу',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'tasks.update',
    availability: 'not-implemented',
    feature: 'F10',
    headers: csrf,
    body: CreateTaskRequestSchema,
    response: TaskSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'patchAdminTask',
    method: 'PATCH',
    path: '/api/v1/admin/tasks/{id}',
    summary: 'Изменить задачу',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'tasks.update',
    availability: 'not-implemented',
    feature: 'F10',
    params: TaskIdParamsSchema,
    headers: versioned,
    body: PatchTaskRequestSchema,
    response: TaskSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'transitionAdminTask',
    method: 'POST',
    path: '/api/v1/admin/tasks/{id}/transitions',
    summary: 'Перевести задачу по статусной модели',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'tasks.transition',
    availability: 'not-implemented',
    feature: 'F10',
    params: TaskIdParamsSchema,
    headers: versioned,
    body: TaskTransitionRequestSchema,
    response: TaskSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'VERSION_CONFLICT', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'linkAdminTaskAppeals',
    method: 'POST',
    path: '/api/v1/admin/tasks/{id}/appeals',
    summary: 'Связать обращения с задачей',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'appeals.link',
    availability: 'not-implemented',
    feature: 'F10',
    params: TaskIdParamsSchema,
    headers: csrf,
    body: LinkAppealsRequestSchema,
    response: TaskSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'commentAdminTask',
    method: 'POST',
    path: '/api/v1/admin/tasks/{id}/comments',
    summary: 'Внутренний комментарий к задаче',
    tags: ['Workflow'],
    auth: 'cookie',
    permission: 'tasks.update',
    availability: 'not-implemented',
    feature: 'F10',
    params: TaskIdParamsSchema,
    headers: csrf,
    body: TaskCommentRequestSchema,
    response: OkSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'requestAppealAnalysis',
    method: 'POST',
    path: '/api/v1/admin/appeals/{id}/analysis',
    summary: 'Поставить анализ обращения в очередь',
    tags: ['Analysis'],
    auth: 'cookie',
    permission: 'analysis.review',
    availability: 'not-implemented',
    feature: 'F14',
    params: AppealIdParamsSchema,
    headers: csrf,
    body: RequestAnalysisRequestSchema,
    response: AnalysisRecordSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getAppealAnalysis',
    method: 'GET',
    path: '/api/v1/admin/appeals/{id}/analysis',
    summary: 'Получить результат анализа',
    tags: ['Analysis'],
    auth: 'cookie',
    permission: 'appeals.read',
    availability: 'not-implemented',
    feature: 'F14',
    params: AppealIdParamsSchema,
    response: AnalysisRecordSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'reviewAppealAnalysis',
    method: 'POST',
    path: '/api/v1/admin/appeals/{id}/analysis/review',
    summary: 'Решение сотрудника по рекомендации LLM',
    tags: ['Analysis'],
    auth: 'cookie',
    permission: 'analysis.review',
    availability: 'not-implemented',
    feature: 'F14',
    params: AppealIdParamsSchema,
    headers: csrf,
    body: ReviewAnalysisRequestSchema,
    response: AnalysisRecordSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'listAppealCandidates',
    method: 'GET',
    path: '/api/v1/admin/appeals/{id}/candidates',
    summary: 'Похожие обращения',
    tags: ['Grouping'],
    auth: 'cookie',
    permission: 'appeals.read',
    availability: 'not-implemented',
    feature: 'F15',
    params: AppealIdParamsSchema,
    response: GroupingCandidatesResponseSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'getTaskPriority',
    method: 'GET',
    path: '/api/v1/admin/tasks/{id}/priority',
    summary: 'Объяснимый приоритет задачи',
    tags: ['Grouping'],
    auth: 'cookie',
    permission: 'tasks.read',
    availability: 'not-implemented',
    feature: 'F15',
    params: TaskIdParamsSchema,
    response: PriorityFactorsSchema,
    errorCodes: ['UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'setTaskPriority',
    method: 'POST',
    path: '/api/v1/admin/tasks/{id}/priority',
    summary: 'Задать ручной приоритет',
    tags: ['Grouping'],
    auth: 'cookie',
    permission: 'tasks.update',
    availability: 'not-implemented',
    feature: 'F15',
    params: TaskIdParamsSchema,
    headers: csrf,
    body: SetPriorityRequestSchema,
    response: PriorityFactorsSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
  {
    operationId: 'mergeAdminTask',
    method: 'POST',
    path: '/api/v1/admin/tasks/{id}/merge',
    summary: 'Объединить задачу в целевую',
    tags: ['Grouping'],
    auth: 'cookie',
    permission: 'tasks.merge',
    availability: 'not-implemented',
    feature: 'F15',
    params: TaskIdParamsSchema,
    headers: csrf,
    body: MergeTasksRequestSchema,
    response: TaskSchema,
    errorCodes: ['SCHEMA_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'FEATURE_NOT_AVAILABLE'],
  },
];
